---
title: "Example of Data Visualization Using  Flexdashboard"
date: June, 12 , 2022
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(knitr)
library(DT)
library(ggprism)


``` 

Column {data-width=600}
-----------------------------------------------------------------------

### Diamond Categories 

```{r echo=FALSE, error=FALSE, fig.cap="Diamond Data 2022", dev='jpeg'}

diamonds %>%
  ggplot(aes(x = carat, y = price , color = color) ) + 
  geom_point(shape = 21, colour = "black") + theme_prism(base_size = 12) + geom_jitter() + 
  facet_wrap(~cut, ncol = 5) + 
  scale_y_continuous(limits = c(0,20500), guide = "prism_offset") + 
  geom_smooth() + 
 scale_colour_brewer(palette = "YlOrRd", direction = -1) + 
    theme(
    axis.text = element_text(colour = "black"), 
    legend.title = element_text()
    
    )
  
```

Column {data-width=350}
-----------------------------------------------------------------------

### Table of Diamond Data 

```{r dev='jpeg'}
dim_price<- diamonds %>% 
  mutate(price_range = case_when(
    price < 5000 ~ "< $5,000", 
    price >=5000 & price< 10000 ~ "$5,000-$10,000",
    price >= 10000 & price <15000 ~ "$10,000-$15,000", 
    price >= 15000 & price <=20000 ~ "$15,000-$20,000"
  ))

dim_price %>% 
  dplyr::select(!c(x,y,z, price, table)) %>% 
  head(1000) %>% 
  DT::datatable(rownames = FALSE)



```

### Price Range of Diamonds 

```{r fig.cap="Diamond Data 2022", dev='jpeg'}

 dim_price%>% 
  ggplot(aes(x = price_range , y = ..count..)) + 
  geom_bar(fill = "#D15821", colour = "black") + theme_prism(base_size = 15) + 
  scale_x_discrete(limits= c("< $5,000", "$5,000-$10,000", "$10,000-$15,000", 
                             "$15,000-$20,000"),
                   guide = "prism_bracket") + 
  scale_y_continuous(guide = "prism_offset") + 
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)
  )
  

```

